name: Build by each push or PR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - uses: actions/upload-artifact@v3
        with:
          name: qb-fix-bilibili.user.js
          path: dist/qb-fix-bilibili.user.js
